### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by eliasmaia** [anu0012/awesome-computer-science-opportunities#42]
Hi there,

I believe there is a mistake in the  link for the Yelp Dataset Challenge. The current link available in the repo is "[Yelp Dataset Challenge](https://www.yelp.com/dataset/challenges)". When you click on it, it shows an 404 error page. 

I quickly googled about the Yelp Dataset Challenge and I guess the actual link would be "[Yelp Dataset Challenge](https://www.yelp.com/dataset/challenge)" 

Thanks again for this great repo with so many useful and interesting information!

**Comment by eliasmaia** [comment]
There's another broken link. 

When we clink on the "IEEEXtreme" link available at the repo, this is what we get:

![iexxxtreme](https://user-images.githubusercontent.com/15288848/56907476-b662e680-6a7a-11e9-988f-7be7bf83bb6f.PNG)

I don't know which link you wanted to show, but I googled about the competition, and apparently this is the official website of [IEEEXtreme](https://ieeextreme.org/). 

Thanks again for the great job in this repo!

**Comment by anu0012** [comment]
Hey, @eliasmaia Thanks for pointing it out. If you like you can create a PR for the same.

**Comment by eliasmaia** [comment]
Thank you! I'll do it! Glad you liked it!
