### ISSUE TITLE
Add Learn Enough to be Dangerous

### ISSUE THREAD

**Issue by eliasmaia** [anu0012/awesome-computer-science-opportunities#46]
I suggest add Learn Enough to be dangerous (https://www.learnenough.com/courses) on the Web Development menu

**Comment by anu0012** [comment]
Hi @eliasmaia Would you like to make a PR?

**Comment by eliasmaia** [comment]
For sure! Thanks!

**Comment by anu0012** [comment]
Thanks @eliasmaia
